# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QT_Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 40, 581, 631))
        self.tabWidget.setObjectName("tabWidget")
        self.tab2D = QtWidgets.QWidget()
        self.tab2D.setObjectName("tab2D")
        self.btnCSV = QtWidgets.QPushButton(self.tab2D)
        self.btnCSV.setGeometry(QtCore.QRect(10, 10, 221, 31))
        self.btnCSV.setObjectName("btnCSV")
        self.lineXPunto = QtWidgets.QLineEdit(self.tab2D)
        self.lineXPunto.setGeometry(QtCore.QRect(30, 50, 51, 31))
        self.lineXPunto.setObjectName("lineXPunto")
        self.lineYPunto = QtWidgets.QLineEdit(self.tab2D)
        self.lineYPunto.setGeometry(QtCore.QRect(110, 50, 51, 31))
        self.lineYPunto.setObjectName("lineYPunto")
        self.btnInsertarPunto = QtWidgets.QPushButton(self.tab2D)
        self.btnInsertarPunto.setGeometry(QtCore.QRect(290, 50, 91, 31))
        self.btnInsertarPunto.setObjectName("btnInsertarPunto")
        self.lblX = QtWidgets.QLabel(self.tab2D)
        self.lblX.setGeometry(QtCore.QRect(10, 50, 21, 21))
        self.lblX.setObjectName("lblX")
        self.lblY = QtWidgets.QLabel(self.tab2D)
        self.lblY.setGeometry(QtCore.QRect(90, 50, 21, 16))
        self.lblY.setObjectName("lblY")
        self.lblEcuacion = QtWidgets.QLabel(self.tab2D)
        self.lblEcuacion.setGeometry(QtCore.QRect(10, 110, 47, 13))
        self.lblEcuacion.setObjectName("lblEcuacion")
        self.lineFuncion = QtWidgets.QLineEdit(self.tab2D)
        self.lineFuncion.setGeometry(QtCore.QRect(10, 130, 561, 31))
        self.lineFuncion.setObjectName("lineFuncion")
        self.btnInsertarFuncion = QtWidgets.QPushButton(self.tab2D)
        self.btnInsertarFuncion.setGeometry(QtCore.QRect(190, 170, 151, 31))
        self.btnInsertarFuncion.setObjectName("btnInsertarFuncion")
        self.lblColorPunto = QtWidgets.QLabel(self.tab2D)
        self.lblColorPunto.setGeometry(QtCore.QRect(170, 50, 31, 16))
        self.lblColorPunto.setObjectName("lblColorPunto")
        self.comboColorPunto = QtWidgets.QComboBox(self.tab2D)
        self.comboColorPunto.setGeometry(QtCore.QRect(200, 50, 81, 31))
        self.comboColorPunto.setObjectName("comboColorPunto")
        self.tabWidget.addTab(self.tab2D, "")
        self.tab3D = QtWidgets.QWidget()
        self.tab3D.setObjectName("tab3D")
        self.tabWidget.addTab(self.tab3D, "")
        self.widgetGrafico = QtWidgets.QWidget(self.centralwidget)
        self.widgetGrafico.setGeometry(QtCore.QRect(600, 60, 600, 600))
        self.widgetGrafico.setObjectName("widgetGrafico")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Legraf"))
        self.btnCSV.setText(_translate("MainWindow", "Importar puntos desde un archivo de texto"))
        self.btnInsertarPunto.setText(_translate("MainWindow", "Insertar Punto"))
        self.lblX.setText(_translate("MainWindow", "X:"))
        self.lblY.setText(_translate("MainWindow", "Y:"))
        self.lblEcuacion.setText(_translate("MainWindow", "Función"))
        self.btnInsertarFuncion.setText(_translate("MainWindow", "Insertar Función"))
        self.lblColorPunto.setText(_translate("MainWindow", "Color:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2D), _translate("MainWindow", "Gráficos 2D"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3D), _translate("MainWindow", "Gráficos 3D"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
